frontend:
  - all:
      - changed-files: ["packages/**/*", "apps/**/*"]
backend:
  - all:
      - changed-files: ["server/**/*"]
documentation:
  - all:
      - changed-files: ["apps/docs/**/*", "**/*.md"]
documentation:
  - all:
      - changed-files: ["pnpm*.yaml", "package*.json"]
.github:
  - all:
      - changed-files: [".github"]
