name: release server

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

env:
  GRADLE_VERSION: 8.3
  JAVA_VERSION: "17"
  JAVA_DISTRIBUTION: "temurin"
  GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true

jobs:
  push-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Clean Build
        run: ./backend/gradle clean build

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ./backend/Dockerfile
          platforms: ${{ secrets.HOST_PLATFORM }}
          build-args: JASYPT_PASSWORD=${{ secrets.JASYPT_PASSWORD }}
          tags: ${{ secrets.DOCKER_IMAGE_TAG }}
          context: ./backend
